export const SUBJECTS = {
  ela: {
    id: 'ela',
    name: 'ELA',
    fullName: 'English Language Arts',
    color: '#F5A623',
    bgClass: 'bg-kk-orange',
    emoji: '📚',
    description: 'Reading, Writing & Language',
  },
  math: {
    id: 'math',
    name: 'Math',
    fullName: 'Mathematics',
    color: '#3CB371',
    bgClass: 'bg-kk-green',
    emoji: '🔢',
    description: 'Numbers, Shapes & Problem Solving',
  },
  science: {
    id: 'science',
    name: 'Science',
    fullName: 'Science',
    color: '#64B5F6',
    bgClass: 'bg-kk-lightblue',
    emoji: '🔬',
    description: 'Explore the Natural World',
  },
  history: {
    id: 'history',
    name: 'History',
    fullName: 'Social Studies & History',
    color: '#F06292',
    bgClass: 'bg-kk-pink',
    emoji: '🌍',
    description: 'People, Places & Events',
  },
};

export const GRADES = ['K', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12'];

// Difficulty label per grade
export function getGradeDifficulty(grade) {
  const g = grade === 'K' ? 0 : parseInt(grade);
  if (g <= 2) return { label: 'Beginner', color: '#3CB371' };
  if (g <= 5) return { label: 'Intermediate', color: '#F5A623' };
  if (g <= 8) return { label: 'Advanced', color: '#64B5F6' };
  return { label: 'Expert', color: '#F06292' };
}

export const LESSONS = {
  ela: {
    K: [
      { id: 'ela-k-1', title: 'Reading Comprehension', subtitle: 'Story Time Adventure', icon: '📖', points: 50, type: 'highlight' },
      { id: 'ela-k-2', title: 'Fact vs Opinion', subtitle: 'Cereal Box Challenge', icon: '🥣', points: 60, type: 'drag-sort' },
      { id: 'ela-k-3', title: 'Main Idea', subtitle: 'Newspaper Hunt', icon: '📰', points: 55, type: 'highlight' },
      { id: 'ela-k-4', title: 'Vocabulary', subtitle: 'Word Market', icon: '🏪', points: 45, type: 'matching' },
      { id: 'ela-k-5', title: 'Parts of Speech', subtitle: 'Label the Lunchbox', icon: '🧺', points: 50, type: 'drag-label' },
      { id: 'ela-k-6', title: 'Story Structure', subtitle: 'Build a Story', icon: '🏗️', points: 60, type: 'sequence' },
      { id: 'ela-k-7', title: 'Rhyming Words', subtitle: 'Rhyme Time Market', icon: '🎵', points: 45, type: 'matching' },
      { id: 'ela-k-8', title: 'Letter Sounds', subtitle: 'Alphabet Kitchen', icon: '🍽️', points: 40, type: 'click-identify' },
      { id: 'ela-k-9', title: 'Sequencing', subtitle: 'Morning Routine Order', icon: '☀️', points: 50, type: 'sequence' },
      { id: 'ela-k-10', title: 'Context Clues', subtitle: 'Mystery Word Box', icon: '📦', points: 55, type: 'highlight' },
      { id: 'ela-k-11', title: 'Author\'s Purpose', subtitle: 'Why Did They Write It?', icon: '✍️', points: 60, type: 'drag-sort' },
      { id: 'ela-k-12', title: 'Point of View', subtitle: 'Who is Telling the Story?', icon: '👀', points: 55, type: 'click-identify' },
      { id: 'ela-k-13', title: 'Summarizing', subtitle: 'The News Report', icon: '📡', points: 60, type: 'journal' },
      { id: 'ela-k-14', title: 'Text Evidence', subtitle: 'Detective Files', icon: '🔍', points: 65, type: 'highlight' },
      { id: 'ela-k-15', title: 'Writing Skills', subtitle: 'My Story Journal', icon: '📝', points: 70, type: 'journal' },
    ],
    1: [
      { id: 'ela-1-1', title: 'Reading Comprehension', subtitle: 'The Lost Puppy Story', icon: '🐕', points: 55, type: 'highlight' },
      { id: 'ela-1-2', title: 'Fact vs Opinion', subtitle: 'Pizza Shop Reviews', icon: '🍕', points: 65, type: 'drag-sort' },
      { id: 'ela-1-3', title: 'Main Idea', subtitle: 'Zoo Brochure Hunt', icon: '🦁', points: 60, type: 'highlight' },
      { id: 'ela-1-4', title: 'Vocabulary', subtitle: 'Grocery Store Words', icon: '🛒', points: 50, type: 'matching' },
      { id: 'ela-1-5', title: 'Nouns & Verbs', subtitle: 'Playground Action Tags', icon: '🛝', points: 55, type: 'drag-label' },
      { id: 'ela-1-6', title: 'Story Structure', subtitle: 'Fairy Tale Builder', icon: '🏰', points: 65, type: 'sequence' },
      { id: 'ela-1-7', title: 'Figurative Language', subtitle: 'Simile Smoothies', icon: '🥤', points: 60, type: 'matching' },
      { id: 'ela-1-8', title: 'Context Clues', subtitle: 'Comic Strip Clues', icon: '💬', points: 60, type: 'highlight' },
      { id: 'ela-1-9', title: 'Author\'s Purpose', subtitle: 'Book Cover Judge', icon: '📚', points: 65, type: 'drag-sort' },
      { id: 'ela-1-10', title: 'Point of View', subtitle: 'The Talking Animals', icon: '🐻', points: 60, type: 'click-identify' },
      { id: 'ela-1-11', title: 'Sequencing', subtitle: 'Recipe Steps', icon: '👩🍳', points: 55, type: 'sequence' },
      { id: 'ela-1-12', title: 'Summarizing', subtitle: 'Movie Poster Maker', icon: '🎬', points: 65, type: 'journal' },
      { id: 'ela-1-13', title: 'Text Evidence', subtitle: 'Science Lab Notes', icon: '🧪', points: 70, type: 'highlight' },
      { id: 'ela-1-14', title: 'Comparing Texts', subtitle: 'Two Books Side by Side', icon: '📊', points: 70, type: 'drag-sort' },
      { id: 'ela-1-15', title: 'Writing Skills', subtitle: 'Postcard from Vacation', icon: '🏖️', points: 75, type: 'journal' },
    ],
    2: [
      { id: 'ela-2-1', title: 'Reading Comprehension', subtitle: 'School Newspaper', icon: '📰', points: 60, type: 'highlight' },
      { id: 'ela-2-2', title: 'Fact vs Opinion', subtitle: 'Sports Card Debate', icon: '⚽', points: 70, type: 'drag-sort' },
      { id: 'ela-2-3', title: 'Main Idea', subtitle: 'Science Magazine', icon: '🔬', points: 65, type: 'highlight' },
      { id: 'ela-2-4', title: 'Vocabulary', subtitle: 'Weather Report Words', icon: '⛅', points: 55, type: 'matching' },
      { id: 'ela-2-5', title: 'Adjectives & Adverbs', subtitle: 'Describe the Scene', icon: '🎨', points: 60, type: 'drag-label' },
      { id: 'ela-2-6', title: 'Story Structure', subtitle: 'Map the Plot Mountain', icon: '⛰️', points: 70, type: 'sequence' },
      { id: 'ela-2-7', title: 'Figurative Language', subtitle: 'Metaphor Menu', icon: '🍽️', points: 65, type: 'matching' },
      { id: 'ela-2-8', title: 'Context Clues', subtitle: 'Recipe Decoder', icon: '👨🍳', points: 65, type: 'highlight' },
      { id: 'ela-2-9', title: 'Author\'s Purpose', subtitle: 'Persuade or Inform?', icon: '📢', points: 70, type: 'drag-sort' },
      { id: 'ela-2-10', title: 'Point of View', subtitle: 'Two Sides of the Story', icon: '⚖️', points: 65, type: 'click-identify' },
      { id: 'ela-2-11', title: 'Sequencing', subtitle: 'Science Experiment Steps', icon: '🧫', points: 60, type: 'sequence' },
      { id: 'ela-2-12', title: 'Summarizing', subtitle: 'Book Review Blog', icon: '💻', points: 70, type: 'journal' },
      { id: 'ela-2-13', title: 'Text Evidence', subtitle: 'Underline the Proof', icon: '🔍', points: 75, type: 'highlight' },
      { id: 'ela-2-14', title: 'Comparing Texts', subtitle: 'Venn Diagram Builder', icon: '🔵', points: 75, type: 'drag-sort' },
      { id: 'ela-2-15', title: 'Writing Skills', subtitle: 'Friendly Letter', icon: '✉️', points: 80, type: 'journal' },
    ],
    3: [
      { id: 'ela-3-1', title: 'Reading Comprehension', subtitle: 'History Article', icon: '📜', points: 65, type: 'highlight' },
      { id: 'ela-3-2', title: 'Fact vs Opinion', subtitle: 'Town Hall Meeting', icon: '🏛️', points: 75, type: 'drag-sort' },
      { id: 'ela-3-3', title: 'Main Idea', subtitle: 'Documentary Notes', icon: '🎥', points: 70, type: 'highlight' },
      { id: 'ela-3-4', title: 'Vocabulary', subtitle: 'Word in Context', icon: '📖', points: 60, type: 'matching' },
      { id: 'ela-3-5', title: 'Parts of Speech', subtitle: 'Sentence Construction', icon: '🔧', points: 65, type: 'drag-label' },
      { id: 'ela-3-6', title: 'Story Structure', subtitle: 'Novel Mapping', icon: '🗺️', points: 75, type: 'sequence' },
      { id: 'ela-3-7', title: 'Figurative Language', subtitle: 'Poetry Garden', icon: '🌸', points: 70, type: 'matching' },
      { id: 'ela-3-8', title: 'Context Clues', subtitle: 'Ancient Text Decoder', icon: '🏺', points: 70, type: 'highlight' },
      { id: 'ela-3-9', title: 'Author\'s Purpose', subtitle: 'Newspaper Editorial', icon: '✒️', points: 75, type: 'drag-sort' },
      { id: 'ela-3-10', title: 'Point of View', subtitle: 'Character Diary', icon: '📓', points: 70, type: 'click-identify' },
      { id: 'ela-3-11', title: 'Sequencing', subtitle: 'Timeline Events', icon: '📅', points: 65, type: 'sequence' },
      { id: 'ela-3-12', title: 'Summarizing', subtitle: 'News Anchor Script', icon: '📡', points: 75, type: 'journal' },
      { id: 'ela-3-13', title: 'Text Evidence', subtitle: 'Courtroom Exhibit', icon: '⚖️', points: 80, type: 'highlight' },
      { id: 'ela-3-14', title: 'Comparing Texts', subtitle: 'Two Authors One Topic', icon: '👥', points: 80, type: 'drag-sort' },
      { id: 'ela-3-15', title: 'Writing Skills', subtitle: 'Opinion Essay', icon: '✍️', points: 85, type: 'journal' },
    ],
    4: [
      { id: 'ela-4-1', title: 'Reading Comprehension', subtitle: 'Scientific Journal', icon: '🔭', points: 70, type: 'highlight' },
      { id: 'ela-4-2', title: 'Fact vs Opinion', subtitle: 'Presidential Debate', icon: '🎤', points: 80, type: 'drag-sort' },
      { id: 'ela-4-3', title: 'Main Idea & Details', subtitle: 'Textbook Analysis', icon: '📗', points: 75, type: 'highlight' },
      { id: 'ela-4-4', title: 'Advanced Vocabulary', subtitle: 'Root Word Lab', icon: '🧬', points: 65, type: 'matching' },
      { id: 'ela-4-5', title: 'Complex Sentences', subtitle: 'Grammar Workshop', icon: '🏭', points: 70, type: 'drag-label' },
      { id: 'ela-4-6', title: 'Story Structure', subtitle: 'Author\'s Blueprint', icon: '📐', points: 80, type: 'sequence' },
      { id: 'ela-4-7', title: 'Figurative Language', subtitle: 'Imagery in Ads', icon: '📺', points: 75, type: 'matching' },
      { id: 'ela-4-8', title: 'Context Clues', subtitle: 'Legal Document', icon: '📋', points: 75, type: 'highlight' },
      { id: 'ela-4-9', title: 'Author\'s Purpose', subtitle: 'Media Literacy Check', icon: '📱', points: 80, type: 'drag-sort' },
      { id: 'ela-4-10', title: 'Point of View', subtitle: 'Historical Perspectives', icon: '⏳', points: 75, type: 'click-identify' },
      { id: 'ela-4-11', title: 'Sequencing', subtitle: 'Cause & Effect Chain', icon: '🔗', points: 70, type: 'sequence' },
      { id: 'ela-4-12', title: 'Summarizing', subtitle: 'Research Abstract', icon: '📝', points: 80, type: 'journal' },
      { id: 'ela-4-13', title: 'Text Evidence', subtitle: 'Debate Evidence File', icon: '📁', points: 85, type: 'highlight' },
      { id: 'ela-4-14', title: 'Comparing Texts', subtitle: 'Genre Study', icon: '📚', points: 85, type: 'drag-sort' },
      { id: 'ela-4-15', title: 'Writing Skills', subtitle: 'Persuasive Letter', icon: '📮', points: 90, type: 'journal' },
    ],
    5: [
      { id: 'ela-5-1', title: 'Reading Comprehension', subtitle: 'Primary Source Documents', icon: '📜', points: 75, type: 'highlight' },
      { id: 'ela-5-2', title: 'Fact vs Opinion', subtitle: 'Social Media Analysis', icon: '💬', points: 85, type: 'drag-sort' },
      { id: 'ela-5-3', title: 'Main Idea & Theme', subtitle: 'Novel Study', icon: '📘', points: 80, type: 'highlight' },
      { id: 'ela-5-4', title: 'Academic Vocabulary', subtitle: 'Domain Words in Context', icon: '🎓', points: 70, type: 'matching' },
      { id: 'ela-5-5', title: 'Parts of Speech', subtitle: 'Complex Sentence Lab', icon: '⚗️', points: 75, type: 'drag-label' },
      { id: 'ela-5-6', title: 'Story Structure', subtitle: 'Screenplay Writing', icon: '🎬', points: 85, type: 'sequence' },
      { id: 'ela-5-7', title: 'Figurative Language', subtitle: 'Song Lyrics Analysis', icon: '🎵', points: 80, type: 'matching' },
      { id: 'ela-5-8', title: 'Context Clues', subtitle: 'Science Report', icon: '🔬', points: 80, type: 'highlight' },
      { id: 'ela-5-9', title: 'Author\'s Purpose', subtitle: 'Bias Detection', icon: '🔍', points: 85, type: 'drag-sort' },
      { id: 'ela-5-10', title: 'Point of View', subtitle: 'Narrator Reliability', icon: '🎭', points: 80, type: 'click-identify' },
      { id: 'ela-5-11', title: 'Sequencing', subtitle: 'Process Analysis', icon: '⚙️', points: 75, type: 'sequence' },
      { id: 'ela-5-12', title: 'Summarizing', subtitle: 'Executive Summary', icon: '💼', points: 85, type: 'journal' },
      { id: 'ela-5-13', title: 'Text Evidence', subtitle: 'Research Citation', icon: '📎', points: 90, type: 'highlight' },
      { id: 'ela-5-14', title: 'Comparing Texts', subtitle: 'Cross-Text Analysis', icon: '⚖️', points: 90, type: 'drag-sort' },
      { id: 'ela-5-15', title: 'Writing Skills', subtitle: 'Argumentative Essay', icon: '✍️', points: 95, type: 'journal' },
    ],
  },
  math: {
    K: [
      { id: 'math-k-1', title: 'Counting', subtitle: 'Count the Apples', icon: '🍎', points: 40, type: 'click-identify' },
      { id: 'math-k-2', title: 'Addition', subtitle: 'Toy Store Add-Up', icon: '🧸', points: 45, type: 'drag-sort' },
      { id: 'math-k-3', title: 'Subtraction', subtitle: 'Cookie Jar Mystery', icon: '🍪', points: 45, type: 'click-identify' },
      { id: 'math-k-4', title: 'Shapes', subtitle: 'Shape Scavenger Hunt', icon: '🔷', points: 40, type: 'click-identify' },
      { id: 'math-k-5', title: 'Measurement', subtitle: 'Who is Taller?', icon: '📏', points: 45, type: 'drag-sort' },
      { id: 'math-k-6', title: 'Numbers 1-10', subtitle: 'Number Line Walk', icon: '🔢', points: 40, type: 'sequence' },
      { id: 'math-k-7', title: 'Patterns', subtitle: 'Bead Pattern Maker', icon: '📿', points: 45, type: 'sequence' },
      { id: 'math-k-8', title: 'Comparing Numbers', subtitle: 'Which Has More?', icon: '⚖️', points: 45, type: 'drag-sort' },
      { id: 'math-k-9', title: 'Time', subtitle: 'Clock Reading', icon: '⏰', points: 50, type: 'click-identify' },
      { id: 'math-k-10', title: 'Money', subtitle: 'Coin Shop', icon: '💰', points: 50, type: 'matching' },
      { id: 'math-k-11', title: 'Place Value', subtitle: 'Tens and Ones Train', icon: '🚂', points: 50, type: 'drag-label' },
      { id: 'math-k-12', title: 'Data & Graphs', subtitle: 'Class Favorite Graph', icon: '📊', points: 50, type: 'click-identify' },
      { id: 'math-k-13', title: 'Word Problems', subtitle: 'Story Math', icon: '📖', points: 55, type: 'journal' },
      { id: 'math-k-14', title: 'Geometry', subtitle: '3D Shape Sorter', icon: '🎲', points: 50, type: 'drag-sort' },
      { id: 'math-k-15', title: 'Estimation', subtitle: 'Guess the Jar', icon: '🫙', points: 55, type: 'click-identify' },
    ],
    1: [
      { id: 'math-1-1', title: 'Addition to 20', subtitle: 'Pet Store Counter', icon: '🐾', points: 50, type: 'click-identify' },
      { id: 'math-1-2', title: 'Subtraction to 20', subtitle: 'Balloon Pop!', icon: '🎈', points: 50, type: 'click-identify' },
      { id: 'math-1-3', title: 'Place Value', subtitle: 'Base-10 Blocks', icon: '🏗️', points: 55, type: 'drag-label' },
      { id: 'math-1-4', title: 'Measurement', subtitle: 'Ruler Room', icon: '📐', points: 55, type: 'matching' },
      { id: 'math-1-5', title: 'Shapes & Geometry', subtitle: 'Shape Factory', icon: '🔺', points: 50, type: 'click-identify' },
      { id: 'math-1-6', title: 'Time', subtitle: 'School Day Schedule', icon: '📅', points: 60, type: 'matching' },
      { id: 'math-1-7', title: 'Money', subtitle: 'Lemonade Stand', icon: '🍋', points: 60, type: 'drag-sort' },
      { id: 'math-1-8', title: 'Data & Graphs', subtitle: 'Weather Tracker', icon: '🌤️', points: 55, type: 'click-identify' },
      { id: 'math-1-9', title: 'Word Problems', subtitle: 'Bakery Math', icon: '🧁', points: 65, type: 'journal' },
      { id: 'math-1-10', title: 'Fractions Intro', subtitle: 'Pizza Fractions', icon: '🍕', points: 60, type: 'click-identify' },
      { id: 'math-1-11', title: 'Estimation', subtitle: 'Library Book Count', icon: '📚', points: 55, type: 'click-identify' },
      { id: 'math-1-12', title: 'Patterns', subtitle: 'Quilt Pattern Design', icon: '🎨', points: 55, type: 'sequence' },
      { id: 'math-1-13', title: 'Algebra Basics', subtitle: 'Missing Number Mystery', icon: '❓', points: 65, type: 'drag-label' },
      { id: 'math-1-14', title: 'Ordinal Numbers', subtitle: 'Race Finish Line', icon: '🏁', points: 50, type: 'sequence' },
      { id: 'math-1-15', title: 'Number Bonds', subtitle: 'Number Family House', icon: '🏠', points: 60, type: 'drag-sort' },
    ],
    2: [
      { id: 'math-2-1', title: 'Addition to 100', subtitle: 'Supermarket Shopping', icon: '🛒', points: 55, type: 'click-identify' },
      { id: 'math-2-2', title: 'Subtraction to 100', subtitle: 'Savings Bank', icon: '🏦', points: 55, type: 'click-identify' },
      { id: 'math-2-3', title: 'Multiplication Intro', subtitle: 'Array Garden', icon: '🌻', points: 65, type: 'drag-sort' },
      { id: 'math-2-4', title: 'Place Value to 1000', subtitle: 'Thousand Block Tower', icon: '🏙️', points: 60, type: 'drag-label' },
      { id: 'math-2-5', title: 'Measurement', subtitle: 'Centimeter & Inch Lab', icon: '🔬', points: 60, type: 'matching' },
      { id: 'math-2-6', title: 'Geometry', subtitle: 'Polygon Town', icon: '🏘️', points: 60, type: 'click-identify' },
      { id: 'math-2-7', title: 'Time', subtitle: 'Daily Planner', icon: '📆', points: 65, type: 'matching' },
      { id: 'math-2-8', title: 'Money', subtitle: 'Toy Catalog Shopping', icon: '🛍️', points: 65, type: 'drag-sort' },
      { id: 'math-2-9', title: 'Fractions', subtitle: 'Sandwich Fractions', icon: '🥪', points: 65, type: 'click-identify' },
      { id: 'math-2-10', title: 'Data & Graphs', subtitle: 'Sports Survey', icon: '🏅', points: 60, type: 'click-identify' },
      { id: 'math-2-11', title: 'Word Problems', subtitle: 'Community Helper Math', icon: '👮', points: 70, type: 'journal' },
      { id: 'math-2-12', title: 'Estimation', subtitle: 'Candy Jar Guess', icon: '🍬', points: 60, type: 'click-identify' },
      { id: 'math-2-13', title: 'Algebra Basics', subtitle: 'Balance Scale Equations', icon: '⚖️', points: 70, type: 'drag-sort' },
      { id: 'math-2-14', title: 'Number Patterns', subtitle: 'Skip Count Racetrack', icon: '🏎️', points: 65, type: 'sequence' },
      { id: 'math-2-15', title: 'Division Intro', subtitle: 'Sharing Snacks', icon: '🍫', points: 70, type: 'drag-sort' },
    ],
    3: [
      { id: 'math-3-1', title: 'Multiplication', subtitle: 'Times Table Restaurant', icon: '🍽️', points: 65, type: 'drag-sort' },
      { id: 'math-3-2', title: 'Division', subtitle: 'Fair Share Farm', icon: '🐄', points: 65, type: 'drag-sort' },
      { id: 'math-3-3', title: 'Fractions', subtitle: 'Fraction Flag Design', icon: '🚩', points: 70, type: 'click-identify' },
      { id: 'math-3-4', title: 'Decimals Intro', subtitle: 'Price Tag Decimals', icon: '🏷️', points: 70, type: 'matching' },
      { id: 'math-3-5', title: 'Place Value to 10,000', subtitle: 'Population Counter', icon: '🌆', points: 65, type: 'drag-label' },
      { id: 'math-3-6', title: 'Geometry', subtitle: 'Architect Blueprint', icon: '📐', points: 65, type: 'click-identify' },
      { id: 'math-3-7', title: 'Area & Perimeter', subtitle: 'Backyard Design', icon: '🏡', points: 75, type: 'drag-sort' },
      { id: 'math-3-8', title: 'Time', subtitle: 'Train Schedule', icon: '🚆', points: 70, type: 'matching' },
      { id: 'math-3-9', title: 'Money & Change', subtitle: 'Cash Register', icon: '💳', points: 75, type: 'drag-sort' },
      { id: 'math-3-10', title: 'Data & Graphs', subtitle: 'Science Fair Results', icon: '📈', points: 70, type: 'click-identify' },
      { id: 'math-3-11', title: 'Word Problems', subtitle: 'Field Trip Budget', icon: '🚌', points: 80, type: 'journal' },
      { id: 'math-3-12', title: 'Estimation', subtitle: 'Construction Estimator', icon: '👷', points: 70, type: 'click-identify' },
      { id: 'math-3-13', title: 'Algebra Basics', subtitle: 'Equation Scales', icon: '⚖️', points: 80, type: 'drag-sort' },
      { id: 'math-3-14', title: 'Measurement', subtitle: 'Cooking with Units', icon: '🧑🍳', points: 70, type: 'matching' },
      { id: 'math-3-15', title: 'Patterns & Rules', subtitle: 'Function Machine', icon: '⚙️', points: 75, type: 'sequence' },
    ],
    4: [
      { id: 'math-4-1', title: 'Multi-Digit Multiplication', subtitle: 'Factory Production', icon: '🏭', points: 75, type: 'drag-label' },
      { id: 'math-4-2', title: 'Long Division', subtitle: 'Warehouse Distribution', icon: '📦', points: 75, type: 'drag-sort' },
      { id: 'math-4-3', title: 'Fractions', subtitle: 'Recipe Scaling', icon: '👨🍳', points: 80, type: 'click-identify' },
      { id: 'math-4-4', title: 'Decimals', subtitle: 'Olympic Scoreboard', icon: '🏆', points: 80, type: 'matching' },
      { id: 'math-4-5', title: 'Place Value to Millions', subtitle: 'National Budget', icon: '🏛️', points: 75, type: 'drag-label' },
      { id: 'math-4-6', title: 'Geometry', subtitle: 'Angle Detective', icon: '🔭', points: 75, type: 'click-identify' },
      { id: 'math-4-7', title: 'Area & Perimeter', subtitle: 'Floor Plan Designer', icon: '🏠', points: 80, type: 'drag-sort' },
      { id: 'math-4-8', title: 'Time Zones', subtitle: 'World Clock', icon: '🌐', points: 80, type: 'matching' },
      { id: 'math-4-9', title: 'Money', subtitle: 'Stock Market Basics', icon: '📊', points: 85, type: 'drag-sort' },
      { id: 'math-4-10', title: 'Data & Graphs', subtitle: 'City Planning Data', icon: '🏙️', points: 80, type: 'click-identify' },
      { id: 'math-4-11', title: 'Word Problems', subtitle: 'Business Math', icon: '💼', points: 90, type: 'journal' },
      { id: 'math-4-12', title: 'Estimation', subtitle: 'Engineering Estimates', icon: '🔧', points: 80, type: 'click-identify' },
      { id: 'math-4-13', title: 'Algebra Basics', subtitle: 'Variable Equations', icon: '🔡', points: 90, type: 'drag-sort' },
      { id: 'math-4-14', title: 'Measurement Conversion', subtitle: 'Unit Converter Tool', icon: '🔄', points: 80, type: 'matching' },
      { id: 'math-4-15', title: 'Coordinate Planes', subtitle: 'Treasure Map Grid', icon: '🗺️', points: 85, type: 'click-identify' },
    ],
    5: [
      { id: 'math-5-1', title: 'Order of Operations', subtitle: 'Calculator Challenge', icon: '🧮', points: 85, type: 'sequence' },
      { id: 'math-5-2', title: 'Fraction Operations', subtitle: 'Kitchen Math', icon: '🍳', points: 85, type: 'click-identify' },
      { id: 'math-5-3', title: 'Decimal Operations', subtitle: 'Gas Station Math', icon: '⛽', points: 85, type: 'matching' },
      { id: 'math-5-4', title: 'Percentages', subtitle: 'Sale Price Calculator', icon: '🏷️', points: 90, type: 'drag-sort' },
      { id: 'math-5-5', title: 'Volume', subtitle: 'Moving Truck Packer', icon: '📦', points: 85, type: 'drag-label' },
      { id: 'math-5-6', title: 'Geometry', subtitle: 'Architect\'s Studio', icon: '🏗️', points: 85, type: 'click-identify' },
      { id: 'math-5-7', title: 'Ratios & Proportions', subtitle: 'Map Scale Reader', icon: '🗺️', points: 90, type: 'matching' },
      { id: 'math-5-8', title: 'Integers', subtitle: 'Temperature Timeline', icon: '🌡️', points: 90, type: 'sequence' },
      { id: 'math-5-9', title: 'Statistics', subtitle: 'Survey Analyzer', icon: '📋', points: 90, type: 'click-identify' },
      { id: 'math-5-10', title: 'Word Problems', subtitle: 'Real Estate Math', icon: '🏘️', points: 95, type: 'journal' },
      { id: 'math-5-11', title: 'Estimation', subtitle: 'Science Lab Estimates', icon: '🧪', points: 85, type: 'click-identify' },
      { id: 'math-5-12', title: 'Pre-Algebra', subtitle: 'Equation Solver', icon: '✏️', points: 95, type: 'drag-sort' },
      { id: 'math-5-13', title: 'Measurement Systems', subtitle: 'Global Recipe Book', icon: '🌎', points: 90, type: 'matching' },
      { id: 'math-5-14', title: 'Coordinate Planes', subtitle: 'City Grid Navigation', icon: '🗺️', points: 90, type: 'click-identify' },
      { id: 'math-5-15', title: 'Data & Probability', subtitle: 'Weather Prediction', icon: '🌦️', points: 95, type: 'click-identify' },
    ],
  },
  science: {
    K: [
      { id: 'sci-k-1', title: 'Living vs Non-Living', subtitle: 'Park Nature Sort', icon: '🌳', points: 45, type: 'drag-sort' },
      { id: 'sci-k-2', title: 'Plants', subtitle: 'Seed to Flower', icon: '🌱', points: 45, type: 'sequence' },
      { id: 'sci-k-3', title: 'Animals', subtitle: 'Animal Habitat Match', icon: '🐻', points: 45, type: 'matching' },
      { id: 'sci-k-4', title: 'Weather', subtitle: 'Weather Station', icon: '🌤️', points: 50, type: 'click-identify' },
      { id: 'sci-k-5', title: 'Seasons', subtitle: 'Four Seasons Sorter', icon: '🍂', points: 45, type: 'drag-sort' },
      { id: 'sci-k-6', title: 'Human Body', subtitle: 'Body Parts Labeler', icon: '🫀', points: 50, type: 'drag-label' },
      { id: 'sci-k-7', title: 'Matter', subtitle: 'Solid Liquid Gas Sorter', icon: '💧', points: 50, type: 'drag-sort' },
      { id: 'sci-k-8', title: 'Scientific Method', subtitle: 'Junior Scientist', icon: '🔬', points: 55, type: 'sequence' },
      { id: 'sci-k-9', title: 'Earth Science', subtitle: 'Land & Water Map', icon: '🌍', points: 50, type: 'click-identify' },
      { id: 'sci-k-10', title: 'Space', subtitle: 'Solar System Explorer', icon: '🚀', points: 55, type: 'click-identify' },
    ],
    1: [
      { id: 'sci-1-1', title: 'Life Science', subtitle: 'Animal Life Cycles', icon: '🦋', points: 55, type: 'sequence' },
      { id: 'sci-1-2', title: 'Plants & Photosynthesis', subtitle: 'Leaf Lab', icon: '🌿', points: 55, type: 'click-identify' },
      { id: 'sci-1-3', title: 'Animals & Habitats', subtitle: 'Wildlife Map', icon: '🦁', points: 55, type: 'matching' },
      { id: 'sci-1-4', title: 'Weather Patterns', subtitle: 'Meteorologist for a Day', icon: '⛈️', points: 60, type: 'drag-sort' },
      { id: 'sci-1-5', title: 'Ecosystems', subtitle: 'Food Web Builder', icon: '🕸️', points: 65, type: 'drag-label' },
      { id: 'sci-1-6', title: 'Human Body', subtitle: 'Organ System Explorer', icon: '🫁', points: 60, type: 'drag-label' },
      { id: 'sci-1-7', title: 'Matter & Properties', subtitle: 'Material Sorter', icon: '🧱', points: 60, type: 'drag-sort' },
      { id: 'sci-1-8', title: 'Forces & Motion', subtitle: 'Push & Pull Playground', icon: '⚽', points: 60, type: 'click-identify' },
      { id: 'sci-1-9', title: 'Earth & Rocks', subtitle: 'Rock Collection', icon: '🪨', points: 60, type: 'drag-sort' },
      { id: 'sci-1-10', title: 'Space', subtitle: 'Moon Phase Tracker', icon: '🌕', points: 65, type: 'sequence' },
    ],
    2: [
      { id: 'sci-2-1', title: 'Life Science', subtitle: 'Adaptations Showcase', icon: '🦎', points: 65, type: 'matching' },
      { id: 'sci-2-2', title: 'Plant Biology', subtitle: 'Parts of a Plant', icon: '🌺', points: 60, type: 'drag-label' },
      { id: 'sci-2-3', title: 'Animal Classifications', subtitle: 'Animal Kingdom Sort', icon: '🐠', points: 65, type: 'drag-sort' },
      { id: 'sci-2-4', title: 'Weather & Climate', subtitle: 'Climate Zone Map', icon: '🌡️', points: 65, type: 'click-identify' },
      { id: 'sci-2-5', title: 'Ecosystems', subtitle: 'Rainforest Layers', icon: '🌲', points: 70, type: 'drag-label' },
      { id: 'sci-2-6', title: 'Human Body Systems', subtitle: 'Digestive Journey', icon: '🍎', points: 70, type: 'sequence' },
      { id: 'sci-2-7', title: 'States of Matter', subtitle: 'Water Cycle Lab', icon: '☁️', points: 65, type: 'sequence' },
      { id: 'sci-2-8', title: 'Physical Science', subtitle: 'Simple Machines Shop', icon: '⚙️', points: 70, type: 'matching' },
      { id: 'sci-2-9', title: 'Earth Science', subtitle: 'Erosion & Weathering', icon: '🏔️', points: 65, type: 'click-identify' },
      { id: 'sci-2-10', title: 'Scientific Method', subtitle: 'Hypothesis Builder', icon: '💡', points: 75, type: 'sequence' },
    ],
    3: [
      { id: 'sci-3-1', title: 'Life Science', subtitle: 'Biome Explorer', icon: '🌍', points: 70, type: 'matching' },
      { id: 'sci-3-2', title: 'Plant Reproduction', subtitle: 'Pollination Station', icon: '🐝', points: 70, type: 'drag-sort' },
      { id: 'sci-3-3', title: 'Animal Behavior', subtitle: 'Wildlife Observation Journal', icon: '🦅', points: 70, type: 'journal' },
      { id: 'sci-3-4', title: 'Earth Science', subtitle: 'Rock Cycle Simulator', icon: '🌋', points: 75, type: 'sequence' },
      { id: 'sci-3-5', title: 'Ecosystems & Food Webs', subtitle: 'Predator-Prey Game', icon: '🦊', points: 80, type: 'drag-sort' },
      { id: 'sci-3-6', title: 'Human Body', subtitle: 'Nervous System Map', icon: '🧠', points: 75, type: 'drag-label' },
      { id: 'sci-3-7', title: 'Chemistry Basics', subtitle: 'Mixing Materials Lab', icon: '🧪', points: 75, type: 'drag-sort' },
      { id: 'sci-3-8', title: 'Forces & Energy', subtitle: 'Roller Coaster Physics', icon: '🎢', points: 80, type: 'click-identify' },
      { id: 'sci-3-9', title: 'Weather Instruments', subtitle: 'Build a Weather Station', icon: '🌬️', points: 75, type: 'matching' },
      { id: 'sci-3-10', title: 'Space Science', subtitle: 'Planet Size Comparison', icon: '🪐', points: 80, type: 'drag-sort' },
    ],
    4: [
      { id: 'sci-4-1', title: 'Ecosystems', subtitle: 'Ecosystem Design', icon: '🌿', points: 80, type: 'drag-sort' },
      { id: 'sci-4-2', title: 'Genetics Intro', subtitle: 'Trait Inheritance Chart', icon: '🧬', points: 80, type: 'drag-label' },
      { id: 'sci-4-3', title: 'Earth Layers', subtitle: 'Core to Crust Drill', icon: '🌍', points: 80, type: 'sequence' },
      { id: 'sci-4-4', title: 'Weather & Climate Change', subtitle: 'Climate Data Analyst', icon: '📊', points: 85, type: 'click-identify' },
      { id: 'sci-4-5', title: 'Chemistry', subtitle: 'Periodic Table Puzzler', icon: '⚗️', points: 85, type: 'matching' },
      { id: 'sci-4-6', title: 'Physics', subtitle: 'Electricity Circuit', icon: '⚡', points: 85, type: 'drag-label' },
      { id: 'sci-4-7', title: 'Human Body', subtitle: 'Heart Rate Lab', icon: '❤️', points: 80, type: 'journal' },
      { id: 'sci-4-8', title: 'Scientific Method', subtitle: 'Full Experiment Design', icon: '🔭', points: 90, type: 'sequence' },
      { id: 'sci-4-9', title: 'Plants Advanced', subtitle: 'Photosynthesis Factory', icon: '🌞', points: 85, type: 'click-identify' },
      { id: 'sci-4-10', title: 'Space', subtitle: 'Solar System Scale', icon: '🌌', points: 90, type: 'drag-sort' },
    ],
    5: [
      { id: 'sci-5-1', title: 'Cell Biology', subtitle: 'Animal vs Plant Cell', icon: '🔬', points: 90, type: 'drag-label' },
      { id: 'sci-5-2', title: 'Ecosystems & Biomes', subtitle: 'Conservation Plan', icon: '🌏', points: 90, type: 'journal' },
      { id: 'sci-5-3', title: 'Earth Science', subtitle: 'Plate Tectonics Map', icon: '🗺️', points: 90, type: 'click-identify' },
      { id: 'sci-5-4', title: 'Climate Science', subtitle: 'Carbon Footprint Calculator', icon: '♻️', points: 95, type: 'journal' },
      { id: 'sci-5-5', title: 'Chemistry', subtitle: 'Chemical Reactions Lab', icon: '🧪', points: 95, type: 'drag-sort' },
      { id: 'sci-5-6', title: 'Physics', subtitle: 'Energy Transfer Simulator', icon: '⚡', points: 95, type: 'sequence' },
      { id: 'sci-5-7', title: 'Human Body', subtitle: 'Body System Connections', icon: '🫀', points: 90, type: 'drag-label' },
      { id: 'sci-5-8', title: 'Scientific Inquiry', subtitle: 'Research Project Design', icon: '📋', points: 100, type: 'sequence' },
      { id: 'sci-5-9', title: 'Genetics & Evolution', subtitle: 'Darwin\'s Finches', icon: '🐦', points: 95, type: 'matching' },
      { id: 'sci-5-10', title: 'Astronomy', subtitle: 'Universe Scale', icon: '🌌', points: 100, type: 'drag-sort' },
    ],
  },
  history: {
    K: [
      { id: 'hist-k-1', title: 'My Community', subtitle: 'Community Helper Map', icon: '🏘️', points: 45, type: 'click-identify' },
      { id: 'hist-k-2', title: 'Timelines', subtitle: 'My Life Timeline', icon: '📅', points: 45, type: 'sequence' },
      { id: 'hist-k-3', title: 'Map Skills', subtitle: 'Classroom Map', icon: '🗺️', points: 50, type: 'click-identify' },
      { id: 'hist-k-4', title: 'American Symbols', subtitle: 'Symbol Match Game', icon: '🦅', points: 50, type: 'matching' },
      { id: 'hist-k-5', title: 'Holidays & Culture', subtitle: 'Holiday Calendar', icon: '🎉', points: 45, type: 'matching' },
      { id: 'hist-k-6', title: 'Family History', subtitle: 'Family Tree Builder', icon: '🌳', points: 50, type: 'drag-sort' },
      { id: 'hist-k-7', title: 'Government Basics', subtitle: 'School Rules & Laws', icon: '📜', points: 50, type: 'drag-sort' },
      { id: 'hist-k-8', title: 'Economics Basics', subtitle: 'Needs vs Wants Sorter', icon: '������', points: 50, type: 'drag-sort' },
      { id: 'hist-k-9', title: 'Geography Basics', subtitle: 'Land & Water Sort', icon: '🌊', points: 50, type: 'drag-sort' },
      { id: 'hist-k-10', title: 'Primary Sources', subtitle: 'Old Photo Detective', icon: '📸', points: 55, type: 'click-identify' },
    ],
    1: [
      { id: 'hist-1-1', title: 'US History', subtitle: 'Pilgrims & Thanksgiving', icon: '🍂', points: 55, type: 'sequence' },
      { id: 'hist-1-2', title: 'American Heroes', subtitle: 'Hero Hall of Fame', icon: '⭐', points: 55, type: 'matching' },
      { id: 'hist-1-3', title: 'Map Skills', subtitle: 'US State Map', icon: '🗺️', points: 60, type: 'click-identify' },
      { id: 'hist-1-4', title: 'Timelines', subtitle: 'American History Timeline', icon: '📜', points: 60, type: 'sequence' },
      { id: 'hist-1-5', title: 'Government', subtitle: 'Three Branches Game', icon: '⚖️', points: 60, type: 'drag-label' },
      { id: 'hist-1-6', title: 'Culture', subtitle: 'World Cultures Market', icon: '🌍', points: 60, type: 'matching' },
      { id: 'hist-1-7', title: 'Economics', subtitle: 'Barter or Buy?', icon: '💰', points: 60, type: 'drag-sort' },
      { id: 'hist-1-8', title: 'Geography', subtitle: 'Continent Sort', icon: '🌎', points: 60, type: 'drag-sort' },
      { id: 'hist-1-9', title: 'Civics', subtitle: 'Voting Simulation', icon: '🗳️', points: 65, type: 'sequence' },
      { id: 'hist-1-10', title: 'Primary Sources', subtitle: 'Declaration Detective', icon: '📋', points: 65, type: 'highlight' },
    ],
    2: [
      { id: 'hist-2-1', title: 'US History', subtitle: 'Colonial America', icon: '🏛️', points: 65, type: 'sequence' },
      { id: 'hist-2-2', title: 'World History', subtitle: 'Ancient Civilizations', icon: '🏺', points: 65, type: 'matching' },
      { id: 'hist-2-3', title: 'Geography', subtitle: 'World Map Explorer', icon: '🌐', points: 65, type: 'click-identify' },
      { id: 'hist-2-4', title: 'Timelines', subtitle: 'Revolutionary War Timeline', icon: '📅', points: 70, type: 'sequence' },
      { id: 'hist-2-5', title: 'Primary Sources', subtitle: 'Read a Historical Letter', icon: '✉️', points: 70, type: 'highlight' },
      { id: 'hist-2-6', title: 'Map Skills', subtitle: 'Physical Map Reading', icon: '🗺️', points: 70, type: 'click-identify' },
      { id: 'hist-2-7', title: 'Government', subtitle: 'Constitution Explorer', icon: '📜', points: 70, type: 'drag-label' },
      { id: 'hist-2-8', title: 'Culture', subtitle: 'Immigration Stories', icon: '🚢', points: 70, type: 'journal' },
      { id: 'hist-2-9', title: 'Economics', subtitle: 'Supply & Demand Market', icon: '📊', points: 70, type: 'drag-sort' },
      { id: 'hist-2-10', title: 'Civics', subtitle: 'Rights & Responsibilities', icon: '⚖️', points: 75, type: 'drag-sort' },
    ],
    3: [
      { id: 'hist-3-1', title: 'US History', subtitle: 'Civil War Journey', icon: '⚔️', points: 75, type: 'sequence' },
      { id: 'hist-3-2', title: 'World History', subtitle: 'Ancient Greece & Rome', icon: '🏛️', points: 75, type: 'matching' },
      { id: 'hist-3-3', title: 'Geography', subtitle: 'Mountain & River Systems', icon: '⛰️', points: 75, type: 'drag-label' },
      { id: 'hist-3-4', title: 'Timelines', subtitle: 'Industrial Revolution', icon: '🏭', points: 80, type: 'sequence' },
      { id: 'hist-3-5', title: 'Primary Sources', subtitle: 'Lincoln\'s Letters', icon: '📜', points: 80, type: 'highlight' },
      { id: 'hist-3-6', title: 'Map Skills', subtitle: 'Trade Route Maps', icon: '🗺️', points: 75, type: 'click-identify' },
      { id: 'hist-3-7', title: 'Government', subtitle: 'Branches of Government', icon: '🏛️', points: 80, type: 'drag-sort' },
      { id: 'hist-3-8', title: 'Culture', subtitle: 'Native American Cultures', icon: '🪶', points: 80, type: 'matching' },
      { id: 'hist-3-9', title: 'Economics', subtitle: 'Westward Expansion Economics', icon: '🤠', points: 80, type: 'journal' },
      { id: 'hist-3-10', title: 'Civics', subtitle: 'Bill of Rights Court Case', icon: '⚖️', points: 85, type: 'drag-sort' },
    ],
    4: [
      { id: 'hist-4-1', title: 'US History', subtitle: 'Civil Rights Movement', icon: '✊', points: 85, type: 'sequence' },
      { id: 'hist-4-2', title: 'World History', subtitle: 'World War Timeline', icon: '🌍', points: 85, type: 'sequence' },
      { id: 'hist-4-3', title: 'Geography', subtitle: 'Economic Geography', icon: '💹', points: 85, type: 'click-identify' },
      { id: 'hist-4-4', title: 'Timelines', subtitle: 'Modern America', icon: '📅', points: 85, type: 'sequence' },
      { id: 'hist-4-5', title: 'Primary Sources', subtitle: 'Analyze a Speech', icon: '🎤', points: 90, type: 'highlight' },
      { id: 'hist-4-6', title: 'Map Skills', subtitle: 'Political Maps', icon: '🗺️', points: 85, type: 'click-identify' },
      { id: 'hist-4-7', title: 'Government', subtitle: 'Electoral College Simulator', icon: '🗳️', points: 90, type: 'drag-sort' },
      { id: 'hist-4-8', title: 'Culture', subtitle: 'Cultural Exchange', icon: '🤝', points: 85, type: 'journal' },
      { id: 'hist-4-9', title: 'Economics', subtitle: 'Global Trade Simulation', icon: '🚢', points: 90, type: 'drag-sort' },
      { id: 'hist-4-10', title: 'Civics', subtitle: 'Create a Law', icon: '📋', points: 95, type: 'journal' },
    ],
    5: [
      { id: 'hist-5-1', title: 'US History', subtitle: 'Vietnam to Today', icon: '🇺🇸', points: 90, type: 'sequence' },
      { id: 'hist-5-2', title: 'World History', subtitle: 'Cold War Diplomacy', icon: '🌐', points: 90, type: 'drag-sort' },
      { id: 'hist-5-3', title: 'Geography', subtitle: 'Geopolitical Analysis', icon: '🗺️', points: 90, type: 'click-identify' },
      { id: 'hist-5-4', title: 'Timelines', subtitle: '21st Century Events', icon: '📅', points: 90, type: 'sequence' },
      { id: 'hist-5-5', title: 'Primary Sources', subtitle: 'Compare Presidential Speeches', icon: '📜', points: 95, type: 'highlight' },
      { id: 'hist-5-6', title: 'Map Skills', subtitle: 'Thematic Map Analysis', icon: '🔍', points: 90, type: 'click-identify' },
      { id: 'hist-5-7', title: 'Government', subtitle: 'Mock Congress', icon: '🏛️', points: 95, type: 'journal' },
      { id: 'hist-5-8', title: 'Culture', subtitle: 'Globalization Impact', icon: '🌍', points: 95, type: 'journal' },
      { id: 'hist-5-9', title: 'Economics', subtitle: 'International Economics', icon: '💹', points: 95, type: 'drag-sort' },
      { id: 'hist-5-10', title: 'Civics', subtitle: 'Constitutional Debate', icon: '⚖️', points: 100, type: 'journal' },
    ],
    6: [
      { id: 'hist-6-1', title: 'Ancient Civilizations', subtitle: 'Mesopotamia & Egypt', icon: '🏺', points: 105, type: 'sequence' },
      { id: 'hist-6-2', title: 'World Religions', subtitle: 'Major Religions Map', icon: '🕌', points: 105, type: 'matching' },
      { id: 'hist-6-3', title: 'Geography', subtitle: 'Physical & Human Geography', icon: '🌐', points: 100, type: 'click-identify' },
      { id: 'hist-6-4', title: 'Economics', subtitle: 'Trade & Barter Systems', icon: '💰', points: 105, type: 'drag-sort' },
      { id: 'hist-6-5', title: 'Government', subtitle: 'City-State vs Empire', icon: '🏛️', points: 110, type: 'matching' },
      { id: 'hist-6-6', title: 'Ancient Greece', subtitle: 'Democracy & Philosophy', icon: '🏛️', points: 105, type: 'sequence' },
      { id: 'hist-6-7', title: 'Ancient Rome', subtitle: 'Republic to Empire', icon: '🦅', points: 105, type: 'drag-sort' },
      { id: 'hist-6-8', title: 'Primary Sources', subtitle: 'Ancient Texts Decoded', icon: '📜', points: 110, type: 'highlight' },
      { id: 'hist-6-9', title: 'Map Skills', subtitle: 'Ancient World Map', icon: '🗺️', points: 100, type: 'click-identify' },
      { id: 'hist-6-10', title: 'Culture & Society', subtitle: 'Daily Life in Ancient Times', icon: '🏺', points: 105, type: 'journal' },
    ],
    7: [
      { id: 'hist-7-1', title: 'Medieval History', subtitle: 'Feudalism & Castles', icon: '🏰', points: 110, type: 'sequence' },
      { id: 'hist-7-2', title: 'Renaissance', subtitle: 'Art & Innovation', icon: '🎨', points: 110, type: 'matching' },
      { id: 'hist-7-3', title: 'Exploration', subtitle: 'Age of Discovery Maps', icon: '🧭', points: 115, type: 'click-identify' },
      { id: 'hist-7-4', title: 'Columbian Exchange', subtitle: 'What Crossed the Ocean?', icon: '⛵', points: 115, type: 'drag-sort' },
      { id: 'hist-7-5', title: 'Primary Sources', subtitle: 'Read a Ship Log', icon: '📜', points: 110, type: 'highlight' },
      { id: 'hist-7-6', title: 'Islamic Golden Age', subtitle: 'Science & Culture', icon: '🌙', points: 110, type: 'matching' },
      { id: 'hist-7-7', title: 'Mongol Empire', subtitle: 'Largest Land Empire', icon: '🐎', points: 110, type: 'sequence' },
      { id: 'hist-7-8', title: 'Reformation', subtitle: 'Church & State', icon: '⛪', points: 115, type: 'drag-sort' },
      { id: 'hist-7-9', title: 'Map Skills', subtitle: 'Medieval Trade Routes', icon: '🗺️', points: 110, type: 'click-identify' },
      { id: 'hist-7-10', title: 'Economics', subtitle: 'Mercantilism & Guilds', icon: '💰', points: 115, type: 'journal' },
    ],
    8: [
      { id: 'hist-8-1', title: 'American Revolution', subtitle: 'Causes & Effects', icon: '🗽', points: 120, type: 'sequence' },
      { id: 'hist-8-2', title: 'Industrial Revolution', subtitle: 'Factory Life Simulation', icon: '🏭', points: 120, type: 'drag-sort' },
      { id: 'hist-8-3', title: 'Reconstruction', subtitle: 'Post-Civil War America', icon: '🔨', points: 125, type: 'highlight' },
      { id: 'hist-8-4', title: 'Immigration', subtitle: 'Ellis Island Stories', icon: '🚢', points: 120, type: 'journal' },
      { id: 'hist-8-5', title: 'Manifest Destiny', subtitle: 'Westward Expansion Map', icon: '🤠', points: 120, type: 'click-identify' },
      { id: 'hist-8-6', title: 'Constitution', subtitle: 'Bill of Rights in Action', icon: '📜', points: 120, type: 'drag-sort' },
      { id: 'hist-8-7', title: 'Civil War', subtitle: 'Battles & Turning Points', icon: '⚔️', points: 125, type: 'sequence' },
      { id: 'hist-8-8', title: 'Primary Sources', subtitle: 'Emancipation Proclamation', icon: '🗝️', points: 125, type: 'highlight' },
      { id: 'hist-8-9', title: 'Economics', subtitle: 'Gilded Age & Labor', icon: '💼', points: 120, type: 'matching' },
      { id: 'hist-8-10', title: 'Civics', subtitle: 'Constitutional Amendments', icon: '⚖️', points: 125, type: 'drag-sort' },
    ],
    9: [
      { id: 'hist-9-1', title: 'World War I', subtitle: 'Causes & Trenches', icon: '⚔️', points: 130, type: 'sequence' },
      { id: 'hist-9-2', title: 'Russian Revolution', subtitle: 'Rise of the USSR', icon: '🌹', points: 130, type: 'matching' },
      { id: 'hist-9-3', title: 'Great Depression', subtitle: 'Economic Collapse', icon: '📉', points: 130, type: 'drag-sort' },
      { id: 'hist-9-4', title: 'Imperialism', subtitle: 'Colonization & Resistance', icon: '🌍', points: 130, type: 'drag-sort' },
      { id: 'hist-9-5', title: 'Primary Sources', subtitle: 'Treaty of Versailles', icon: '📜', points: 130, type: 'highlight' },
      { id: 'hist-9-6', title: 'Rise of Fascism', subtitle: 'Italy, Germany & Spain', icon: '⚠️', points: 135, type: 'sequence' },
      { id: 'hist-9-7', title: 'Roaring Twenties', subtitle: 'Culture & Prosperity', icon: '🎶', points: 130, type: 'journal' },
      { id: 'hist-9-8', title: 'New Deal', subtitle: 'FDR\'s Recovery Plan', icon: '🏗️', points: 130, type: 'drag-sort' },
      { id: 'hist-9-9', title: 'Map Skills', subtitle: 'WWI Allied vs Central Powers', icon: '🗺️', points: 130, type: 'click-identify' },
      { id: 'hist-9-10', title: 'Economics', subtitle: 'Stock Market Crash Analysis', icon: '📊', points: 135, type: 'journal' },
    ],
    10: [
      { id: 'hist-10-1', title: 'World War II', subtitle: 'Global Conflict Analysis', icon: '🌍', points: 140, type: 'sequence' },
      { id: 'hist-10-2', title: 'Holocaust', subtitle: 'Primary Source Study', icon: '📖', points: 140, type: 'highlight' },
      { id: 'hist-10-3', title: 'Cold War', subtitle: 'Superpowers Divide', icon: '🌐', points: 145, type: 'matching' },
      { id: 'hist-10-4', title: 'Decolonization', subtitle: 'Independence Movements', icon: '🌍', points: 140, type: 'drag-sort' },
      { id: 'hist-10-5', title: 'Korean War', subtitle: 'Forgotten War Analysis', icon: '⚔️', points: 140, type: 'sequence' },
      { id: 'hist-10-6', title: 'Space Race', subtitle: 'NASA vs USSR', icon: '🚀', points: 140, type: 'matching' },
      { id: 'hist-10-7', title: 'United Nations', subtitle: 'Building World Peace', icon: '🕊️', points: 145, type: 'journal' },
      { id: 'hist-10-8', title: 'Primary Sources', subtitle: 'Churchill & Roosevelt Letters', icon: '📜', points: 140, type: 'highlight' },
      { id: 'hist-10-9', title: 'Hiroshima', subtitle: 'Ethics of Atomic Bomb', icon: '☢️', points: 145, type: 'journal' },
      { id: 'hist-10-10', title: 'Map Skills', subtitle: 'Cold War Alliances Map', icon: '🗺️', points: 140, type: 'click-identify' },
    ],
    11: [
      { id: 'hist-11-1', title: 'Civil Rights Era', subtitle: 'Marches & Legislation', icon: '✊', points: 150, type: 'highlight' },
      { id: 'hist-11-2', title: 'Vietnam War', subtitle: 'Conflict & Protest', icon: '🕊️', points: 150, type: 'drag-sort' },
      { id: 'hist-11-3', title: 'Modern America', subtitle: 'Reagan to Obama', icon: '🇺🇸', points: 155, type: 'sequence' },
      { id: 'hist-11-4', title: 'Women\'s Rights', subtitle: 'Suffrage to Now', icon: '♀️', points: 150, type: 'sequence' },
      { id: 'hist-11-5', title: '9/11 & War on Terror', subtitle: 'America After 2001', icon: '🕯️', points: 155, type: 'highlight' },
      { id: 'hist-11-6', title: 'Watergate', subtitle: 'Power & Accountability', icon: '🏛️', points: 150, type: 'drag-sort' },
      { id: 'hist-11-7', title: 'Primary Sources', subtitle: 'MLK vs Malcolm X Speeches', icon: '📜', points: 155, type: 'highlight' },
      { id: 'hist-11-8', title: 'Economics', subtitle: 'Reagan Economics Debate', icon: '📊', points: 150, type: 'journal' },
      { id: 'hist-11-9', title: 'AP US History', subtitle: 'DBQ Practice', icon: '📝', points: 155, type: 'journal' },
      { id: 'hist-11-10', title: 'Civics', subtitle: 'Landmark Supreme Court Cases', icon: '⚖️', points: 155, type: 'matching' },
    ],
    12: [
      { id: 'hist-12-1', title: 'Geopolitics Today', subtitle: 'Current Global Issues', icon: '🌐', points: 160, type: 'journal' },
      { id: 'hist-12-2', title: 'Comparative Government', subtitle: 'Democracy vs Autocracy', icon: '⚖️', points: 165, type: 'matching' },
      { id: 'hist-12-3', title: 'Senior Capstone', subtitle: 'History Research Project', icon: '🏆', points: 170, type: 'journal' },
      { id: 'hist-12-4', title: 'Middle East Conflicts', subtitle: 'Israeli-Palestinian Context', icon: '🕌', points: 165, type: 'drag-sort' },
      { id: 'hist-12-5', title: 'Rise of China', subtitle: 'Economic & Political Power', icon: '🐉', points: 165, type: 'sequence' },
      { id: 'hist-12-6', title: 'Climate Policy', subtitle: 'Paris Agreement & Beyond', icon: '🌱', points: 160, type: 'journal' },
      { id: 'hist-12-7', title: 'AP Gov & Politics', subtitle: 'Federalism & Elections', icon: '🗳️', points: 165, type: 'drag-sort' },
      { id: 'hist-12-8', title: 'Economic Systems', subtitle: 'Capitalism vs Socialism', icon: '💹', points: 165, type: 'matching' },
      { id: 'hist-12-9', title: 'Social Movements', subtitle: 'MeToo, BLM & Beyond', icon: '✊', points: 165, type: 'journal' },
      { id: 'hist-12-10', title: 'Future of Democracy', subtitle: 'Disinformation & Media', icon: '📱', points: 165, type: 'journal' },
    ],
  },
};

// Add grades 6-12 to ELA
LESSONS.ela[6] = [
  { id: 'ela-6-1', title: 'Literary Analysis', subtitle: 'Novel Dissection', icon: '📘', points: 100, type: 'highlight' },
  { id: 'ela-6-2', title: 'Research Writing', subtitle: 'Topic Investigation', icon: '🔍', points: 105, type: 'journal' },
  { id: 'ela-6-3', title: 'Grammar & Mechanics', subtitle: 'Advanced Grammar Lab', icon: '✏️', points: 95, type: 'drag-label' },
  { id: 'ela-6-4', title: 'Rhetoric & Persuasion', subtitle: 'Ad Analysis', icon: '📢', points: 105, type: 'drag-sort' },
  { id: 'ela-6-5', title: 'Poetry', subtitle: 'Poem Breakdown', icon: '🎭', points: 100, type: 'highlight' },
  { id: 'ela-6-6', title: 'Fact vs Opinion', subtitle: 'News Media Check', icon: '📰', points: 100, type: 'drag-sort' },
  { id: 'ela-6-7', title: 'Vocabulary', subtitle: 'Latin Root Explorer', icon: '🏛️', points: 95, type: 'matching' },
  { id: 'ela-6-8', title: 'Narrative Writing', subtitle: 'Short Story Workshop', icon: '📖', points: 110, type: 'journal' },
  { id: 'ela-6-9', title: 'Text Structures', subtitle: 'Compare & Contrast Map', icon: '🗂️', points: 100, type: 'drag-sort' },
  { id: 'ela-6-10', title: 'Context Clues', subtitle: 'Science Article Decoding', icon: '🧪', points: 100, type: 'highlight' },
  { id: 'ela-6-11', title: 'Author\'s Craft', subtitle: 'How Authors Build Suspense', icon: '🕵️', points: 105, type: 'highlight' },
  { id: 'ela-6-12', title: 'Summarizing', subtitle: 'Chapter Summary Challenge', icon: '📝', points: 100, type: 'journal' },
];
LESSONS.ela[7] = [
  { id: 'ela-7-1', title: 'Argumentative Writing', subtitle: 'Debate Prep', icon: '⚖️', points: 110, type: 'journal' },
  { id: 'ela-7-2', title: 'Theme Analysis', subtitle: 'Across Texts', icon: '📚', points: 110, type: 'highlight' },
  { id: 'ela-7-3', title: 'Figurative Language', subtitle: 'Literary Devices Deep Dive', icon: '🎨', points: 105, type: 'matching' },
  { id: 'ela-7-4', title: 'Informational Text', subtitle: 'Article Deconstruction', icon: '📰', points: 110, type: 'drag-sort' },
  { id: 'ela-7-5', title: 'Vocabulary in Context', subtitle: 'Academic Word Wall', icon: '🏛️', points: 100, type: 'matching' },
  { id: 'ela-7-6', title: 'Point of View', subtitle: 'Unreliable Narrator Lab', icon: '👁️', points: 110, type: 'click-identify' },
  { id: 'ela-7-7', title: 'Research Skills', subtitle: 'Finding Credible Sources', icon: '🔎', points: 110, type: 'drag-sort' },
  { id: 'ela-7-8', title: 'Grammar Deep Dive', subtitle: 'Clauses & Phrases', icon: '✍️', points: 105, type: 'drag-label' },
  { id: 'ela-7-9', title: 'Narrative Writing', subtitle: 'Dialogue & Pacing', icon: '💬', points: 115, type: 'journal' },
  { id: 'ela-7-10', title: 'Poetry Analysis', subtitle: 'Sonnet Breakdown', icon: '🌹', points: 110, type: 'highlight' },
  { id: 'ela-7-11', title: 'Text Evidence', subtitle: 'Textual Support Lab', icon: '📋', points: 110, type: 'highlight' },
  { id: 'ela-7-12', title: 'Media Literacy', subtitle: 'Is This Real News?', icon: '📡', points: 115, type: 'drag-sort' },
];
LESSONS.ela[8] = [
  { id: 'ela-8-1', title: 'Literary Criticism', subtitle: 'Critical Lens Essay', icon: '🔬', points: 120, type: 'journal' },
  { id: 'ela-8-2', title: 'Syntax & Style', subtitle: 'Sentence Variety Lab', icon: '✍️', points: 115, type: 'drag-label' },
  { id: 'ela-8-3', title: 'Research Skills', subtitle: 'MLA Citation Builder', icon: '📎', points: 120, type: 'journal' },
  { id: 'ela-8-4', title: 'Theme & Symbolism', subtitle: 'Symbols in Literature', icon: '🔮', points: 120, type: 'highlight' },
  { id: 'ela-8-5', title: 'Argumentative Essay', subtitle: 'Claim Evidence Reasoning', icon: '⚖️', points: 125, type: 'journal' },
  { id: 'ela-8-6', title: 'Vocabulary', subtitle: 'Greek & Latin Roots', icon: '🏺', points: 115, type: 'matching' },
  { id: 'ela-8-7', title: 'Poetry Writing', subtitle: 'Free Verse & Structure', icon: '🎵', points: 120, type: 'journal' },
  { id: 'ela-8-8', title: 'Text Structures', subtitle: 'Complex Text Analysis', icon: '🗂️', points: 120, type: 'drag-sort' },
  { id: 'ela-8-9', title: 'Author\'s Purpose', subtitle: 'Political Cartoon Analysis', icon: '🗳️', points: 120, type: 'drag-sort' },
  { id: 'ela-8-10', title: 'Comparing Texts', subtitle: 'Book vs Film Analysis', icon: '🎬', points: 125, type: 'highlight' },
  { id: 'ela-8-11', title: 'Narrative Techniques', subtitle: 'Flashback & Foreshadowing', icon: '⏳', points: 120, type: 'click-identify' },
  { id: 'ela-8-12', title: 'Public Speaking', subtitle: 'Speech Outline Builder', icon: '🎤', points: 125, type: 'sequence' },
];
LESSONS.ela[9] = [
  { id: 'ela-9-1', title: 'Classical Literature', subtitle: 'Shakespeare Intro', icon: '🎭', points: 130, type: 'highlight' },
  { id: 'ela-9-2', title: 'Analytical Essay', subtitle: 'Five-Paragraph Mastery', icon: '📝', points: 130, type: 'journal' },
  { id: 'ela-9-3', title: 'Rhetoric', subtitle: 'Ethos Pathos Logos', icon: '📢', points: 125, type: 'matching' },
  { id: 'ela-9-4', title: 'World Mythology', subtitle: 'Hero\'s Journey Map', icon: '🗺️', points: 130, type: 'sequence' },
  { id: 'ela-9-5', title: 'Short Story Analysis', subtitle: 'Plot Device Identifier', icon: '🔍', points: 125, type: 'drag-sort' },
  { id: 'ela-9-6', title: 'Grammar & Style', subtitle: 'Voice & Tone Workshop', icon: '🖋️', points: 130, type: 'journal' },
  { id: 'ela-9-7', title: 'Vocabulary', subtitle: 'SAT Word Strategies', icon: '🎓', points: 130, type: 'matching' },
  { id: 'ela-9-8', title: 'Reading Comprehension', subtitle: 'Inference & Evidence', icon: '📖', points: 130, type: 'highlight' },
  { id: 'ela-9-9', title: 'Research Paper', subtitle: 'MLA Format Master', icon: '📄', points: 135, type: 'journal' },
  { id: 'ela-9-10', title: 'Creative Writing', subtitle: 'Short Story Draft', icon: '✏️', points: 130, type: 'journal' },
];
LESSONS.ela[10] = [
  { id: 'ela-10-1', title: 'World Literature', subtitle: 'Cross-Cultural Texts', icon: '🌍', points: 140, type: 'highlight' },
  { id: 'ela-10-2', title: 'Extended Essay', subtitle: 'Research Paper', icon: '📄', points: 145, type: 'journal' },
  { id: 'ela-10-3', title: 'Shakespeare', subtitle: 'Hamlet Character Study', icon: '🎭', points: 140, type: 'highlight' },
  { id: 'ela-10-4', title: 'Rhetorical Analysis', subtitle: 'Presidential Speech', icon: '🎤', points: 140, type: 'drag-sort' },
  { id: 'ela-10-5', title: 'Literary Movements', subtitle: 'Romanticism to Modernism', icon: '📚', points: 140, type: 'sequence' },
  { id: 'ela-10-6', title: 'Comparative Literature', subtitle: 'Two Novels, One Theme', icon: '⚖️', points: 145, type: 'journal' },
  { id: 'ela-10-7', title: 'Vocabulary', subtitle: 'Advanced Academic Words', icon: '🔤', points: 135, type: 'matching' },
  { id: 'ela-10-8', title: 'Research Skills', subtitle: 'Annotated Bibliography', icon: '📎', points: 140, type: 'journal' },
];
LESSONS.ela[11] = [
  { id: 'ela-11-1', title: 'American Literature', subtitle: 'Canon Study', icon: '🗽', points: 150, type: 'highlight' },
  { id: 'ela-11-2', title: 'AP Language Skills', subtitle: 'Synthesis Essay', icon: '🎓', points: 155, type: 'journal' },
  { id: 'ela-11-3', title: 'Tone & Diction', subtitle: 'Author Voice Analysis', icon: '🎙️', points: 150, type: 'highlight' },
  { id: 'ela-11-4', title: 'The Great Gatsby', subtitle: 'Symbolism & Theme', icon: '🥂', points: 150, type: 'drag-sort' },
  { id: 'ela-11-5', title: 'Argumentative Research', subtitle: 'Op-Ed Writing Workshop', icon: '🗞️', points: 155, type: 'journal' },
  { id: 'ela-11-6', title: 'AP Multiple Choice', subtitle: 'Passage Practice', icon: '📋', points: 150, type: 'click-identify' },
  { id: 'ela-11-7', title: 'Vocab in Context', subtitle: 'College-Level Words', icon: '📖', points: 145, type: 'matching' },
  { id: 'ela-11-8', title: 'Satire & Irony', subtitle: 'Swift & Twain Analysis', icon: '😏', points: 155, type: 'highlight' },
];
LESSONS.ela[12] = [
  { id: 'ela-12-1', title: 'British Literature', subtitle: 'Chaucer to Orwell', icon: '🏰', points: 160, type: 'highlight' },
  { id: 'ela-12-2', title: 'Senior Capstone', subtitle: 'Independent Research', icon: '🏆', points: 170, type: 'journal' },
  { id: 'ela-12-3', title: 'AP Literature', subtitle: 'Prose Essay Mastery', icon: '🖊️', points: 165, type: 'journal' },
  { id: 'ela-12-4', title: '1984 Analysis', subtitle: 'Dystopia & Power', icon: '👁️', points: 160, type: 'highlight' },
  { id: 'ela-12-5', title: 'College Essay', subtitle: 'Personal Statement Draft', icon: '🎓', points: 165, type: 'journal' },
  { id: 'ela-12-6', title: 'Postmodern Literature', subtitle: 'Nonlinear Narrative', icon: '🌀', points: 165, type: 'highlight' },
  { id: 'ela-12-7', title: 'AP Practice Exam', subtitle: 'Full Passage Analysis', icon: '📝', points: 160, type: 'click-identify' },
  { id: 'ela-12-8', title: 'Ethics in Writing', subtitle: 'Plagiarism & Voice', icon: '⚖️', points: 160, type: 'journal' },
];

// Add grades 6-12 to Math
LESSONS.math[6] = [
  { id: 'math-6-1', title: 'Ratios & Proportions', subtitle: 'Recipe Scaling Lab', icon: '🧪', points: 100, type: 'matching' },
  { id: 'math-6-2', title: 'Expressions & Equations', subtitle: 'Variable Explorer', icon: '🔡', points: 100, type: 'drag-sort' },
  { id: 'math-6-3', title: 'Geometry', subtitle: 'Net Folding Factory', icon: '📦', points: 95, type: 'click-identify' },
  { id: 'math-6-4', title: 'Statistics', subtitle: 'Data Collection & Display', icon: '📊', points: 100, type: 'drag-sort' },
  { id: 'math-6-5', title: 'Number Systems', subtitle: 'Negative Number Line', icon: '🌡️', points: 95, type: 'sequence' },
  { id: 'math-6-6', title: 'Fractions & Decimals', subtitle: 'Conversion Station', icon: '🔄', points: 100, type: 'matching' },
  { id: 'math-6-7', title: 'Percentages', subtitle: 'Tip Calculator', icon: '💰', points: 100, type: 'click-identify' },
  { id: 'math-6-8', title: 'Area & Perimeter', subtitle: 'School Garden Design', icon: '🌻', points: 100, type: 'drag-sort' },
  { id: 'math-6-9', title: 'Integers', subtitle: 'Elevation & Temperature', icon: '⛰️', points: 100, type: 'sequence' },
  { id: 'math-6-10', title: 'Word Problems', subtitle: 'Community Budget', icon: '🏘️', points: 105, type: 'journal' },
  { id: 'math-6-11', title: 'Order of Operations', subtitle: 'Expression Builder', icon: '🧮', points: 100, type: 'sequence' },
  { id: 'math-6-12', title: 'Data & Probability', subtitle: 'Spin the Wheel', icon: '🎡', points: 105, type: 'click-identify' },
];
LESSONS.math[7] = [
  { id: 'math-7-1', title: 'Proportional Reasoning', subtitle: 'Unit Rate Market', icon: '🏪', points: 110, type: 'drag-sort' },
  { id: 'math-7-2', title: 'Pre-Algebra', subtitle: 'Two-Step Equations', icon: '⚙️', points: 110, type: 'drag-label' },
  { id: 'math-7-3', title: 'Geometry', subtitle: 'Area & Volume Mastery', icon: '📐', points: 110, type: 'click-identify' },
  { id: 'math-7-4', title: 'Probability', subtitle: 'Game Show Probability', icon: '🎲', points: 115, type: 'matching' },
  { id: 'math-7-5', title: 'Rational Numbers', subtitle: 'Number Line Navigation', icon: '📏', points: 110, type: 'sequence' },
  { id: 'math-7-6', title: 'Scale & Drawing', subtitle: 'Architect Mini Maps', icon: '🗺️', points: 110, type: 'click-identify' },
  { id: 'math-7-7', title: 'Percents', subtitle: 'Discount & Tax Simulator', icon: '🏷️', points: 115, type: 'drag-sort' },
  { id: 'math-7-8', title: 'Statistics', subtitle: 'Mean, Median, Mode Lab', icon: '📊', points: 110, type: 'click-identify' },
  { id: 'math-7-9', title: 'Inequalities', subtitle: 'Number Line Challenges', icon: '⚖️', points: 115, type: 'sequence' },
  { id: 'math-7-10', title: 'Word Problems', subtitle: 'Real-World Algebra', icon: '💡', points: 115, type: 'journal' },
];
LESSONS.math[8] = [
  { id: 'math-8-1', title: 'Linear Equations', subtitle: 'Graphing Stories', icon: '📈', points: 120, type: 'sequence' },
  { id: 'math-8-2', title: 'Functions', subtitle: 'Input-Output Machine', icon: '⚙️', points: 120, type: 'drag-sort' },
  { id: 'math-8-3', title: 'Pythagorean Theorem', subtitle: 'Right Triangle Builder', icon: '📐', points: 125, type: 'click-identify' },
  { id: 'math-8-4', title: 'Statistics', subtitle: 'Scatter Plot Analysis', icon: '📊', points: 120, type: 'click-identify' },
  { id: 'math-8-5', title: 'Systems of Equations', subtitle: 'Intersection Finder', icon: '🔀', points: 125, type: 'drag-sort' },
  { id: 'math-8-6', title: 'Exponents', subtitle: 'Powers of 10 Lab', icon: '⚡', points: 120, type: 'sequence' },
  { id: 'math-8-7', title: 'Transformations', subtitle: 'Slide, Flip, Turn', icon: '🔄', points: 120, type: 'click-identify' },
  { id: 'math-8-8', title: 'Volume', subtitle: '3D Shape Calculator', icon: '📦', points: 125, type: 'matching' },
  { id: 'math-8-9', title: 'Word Problems', subtitle: 'Real World Linear Models', icon: '🌍', points: 130, type: 'journal' },
  { id: 'math-8-10', title: 'Scientific Notation', subtitle: 'Astronomy Numbers', icon: '🌌', points: 125, type: 'drag-label' },
];
LESSONS.math[9] = [
  { id: 'math-9-1', title: 'Algebra I', subtitle: 'Quadratic Equations', icon: '📉', points: 130, type: 'drag-sort' },
  { id: 'math-9-2', title: 'Geometry', subtitle: 'Proof Writing', icon: '📐', points: 135, type: 'sequence' },
  { id: 'math-9-3', title: 'Statistics', subtitle: 'Normal Distribution', icon: '📊', points: 130, type: 'click-identify' },
  { id: 'math-9-4', title: 'Linear vs Exponential', subtitle: 'Population Growth', icon: '📈', points: 130, type: 'matching' },
  { id: 'math-9-5', title: 'Factoring', subtitle: 'Trinomial Puzzles', icon: '🧩', points: 135, type: 'sequence' },
  { id: 'math-9-6', title: 'Coordinate Geometry', subtitle: 'Distance & Midpoint', icon: '🗺️', points: 130, type: 'click-identify' },
  { id: 'math-9-7', title: 'Inequalities', subtitle: 'System of Inequalities', icon: '⚖️', points: 130, type: 'drag-sort' },
  { id: 'math-9-8', title: 'Word Problems', subtitle: 'Algebra in Real Life', icon: '💡', points: 135, type: 'journal' },
];
LESSONS.math[10] = [
  { id: 'math-10-1', title: 'Algebra II', subtitle: 'Polynomials & Factoring', icon: '🧮', points: 140, type: 'sequence' },
  { id: 'math-10-2', title: 'Trigonometry', subtitle: 'Unit Circle Explorer', icon: '⭕', points: 145, type: 'matching' },
  { id: 'math-10-3', title: 'Logarithms', subtitle: 'Earthquake Scale Math', icon: '📉', points: 140, type: 'click-identify' },
  { id: 'math-10-4', title: 'Complex Numbers', subtitle: 'Imaginary Number Lab', icon: '🔮', points: 145, type: 'drag-sort' },
  { id: 'math-10-5', title: 'Conic Sections', subtitle: 'Circles & Parabolas', icon: '⭕', points: 145, type: 'sequence' },
  { id: 'math-10-6', title: 'Sequences & Series', subtitle: 'Fibonacci & Beyond', icon: '🌀', points: 140, type: 'matching' },
  { id: 'math-10-7', title: 'Statistics', subtitle: 'Regression Analysis', icon: '📊', points: 140, type: 'click-identify' },
  { id: 'math-10-8', title: 'Word Problems', subtitle: 'Advanced Applications', icon: '🌍', points: 145, type: 'journal' },
];
LESSONS.math[11] = [
  { id: 'math-11-1', title: 'Pre-Calculus', subtitle: 'Functions & Limits Intro', icon: '📈', points: 155, type: 'sequence' },
  { id: 'math-11-2', title: 'Statistics', subtitle: 'Inferential Stats', icon: '📊', points: 150, type: 'drag-sort' },
  { id: 'math-11-3', title: 'Trig Applications', subtitle: 'Wave & Periodic Functions', icon: '〰️', points: 155, type: 'click-identify' },
  { id: 'math-11-4', title: 'Matrices', subtitle: 'Data Transformation', icon: '🔢', points: 155, type: 'drag-sort' },
  { id: 'math-11-5', title: 'Limits', subtitle: 'Approaching Infinity', icon: '♾️', points: 155, type: 'sequence' },
  { id: 'math-11-6', title: 'Probability', subtitle: 'Combinatorics & Counting', icon: '🎲', points: 150, type: 'matching' },
  { id: 'math-11-7', title: 'Vectors', subtitle: 'Direction & Magnitude', icon: '➡️', points: 155, type: 'drag-label' },
  { id: 'math-11-8', title: 'Word Problems', subtitle: 'Pre-Calc Modeling', icon: '🏗️', points: 160, type: 'journal' },
];
LESSONS.math[12] = [
  { id: 'math-12-1', title: 'Calculus', subtitle: 'Derivatives & Integrals', icon: '∫', points: 165, type: 'journal' },
  { id: 'math-12-2', title: 'Senior Math', subtitle: 'Real World Applications', icon: '🌍', points: 170, type: 'journal' },
  { id: 'math-12-3', title: 'AP Calculus', subtitle: 'FRQ Practice', icon: '📝', points: 170, type: 'journal' },
  { id: 'math-12-4', title: 'Integration', subtitle: 'Area Under Curves', icon: '📈', points: 165, type: 'sequence' },
  { id: 'math-12-5', title: 'Differential Equations', subtitle: 'Growth Models', icon: '🌱', points: 170, type: 'click-identify' },
  { id: 'math-12-6', title: 'Statistics AP', subtitle: 'Hypothesis Testing', icon: '📊', points: 165, type: 'drag-sort' },
  { id: 'math-12-7', title: 'Senior Capstone', subtitle: 'Math Research Project', icon: '🏆', points: 175, type: 'journal' },
];

// Add grades 6-12 to Science
LESSONS.science[6] = [
  { id: 'sci-6-1', title: 'Life Science', subtitle: 'Cell Structure & Function', icon: '🔬', points: 100, type: 'drag-label' },
  { id: 'sci-6-2', title: 'Earth Science', subtitle: 'Rock Cycle Deep Dive', icon: '🌋', points: 100, type: 'sequence' },
  { id: 'sci-6-3', title: 'Physical Science', subtitle: 'Force & Energy Lab', icon: '⚡', points: 100, type: 'click-identify' },
  { id: 'sci-6-4', title: 'Scientific Method', subtitle: 'Design an Experiment', icon: '🧪', points: 105, type: 'sequence' },
  { id: 'sci-6-5', title: 'Ecosystems', subtitle: 'Food Web Challenge', icon: '🕸️', points: 100, type: 'drag-sort' },
  { id: 'sci-6-6', title: 'Weather & Climate', subtitle: 'Weather Pattern Tracker', icon: '🌦️', points: 100, type: 'click-identify' },
  { id: 'sci-6-7', title: 'Astronomy', subtitle: 'Stars & Constellations', icon: '⭐', points: 105, type: 'matching' },
  { id: 'sci-6-8', title: 'Human Body', subtitle: 'Body Systems Overview', icon: '🫀', points: 100, type: 'drag-label' },
  { id: 'sci-6-9', title: 'Matter & Energy', subtitle: 'States of Matter Lab', icon: '🧊', points: 100, type: 'drag-sort' },
  { id: 'sci-6-10', title: 'Environment', subtitle: 'Pollution & Solutions', icon: '♻️', points: 105, type: 'journal' },
];
LESSONS.science[7] = [
  { id: 'sci-7-1', title: 'Life Science', subtitle: 'Genetics & Heredity', icon: '🧬', points: 110, type: 'matching' },
  { id: 'sci-7-2', title: 'Earth Science', subtitle: 'Plate Tectonics Simulator', icon: '🗺️', points: 110, type: 'click-identify' },
  { id: 'sci-7-3', title: 'Physical Science', subtitle: 'Chemical Bonds Lab', icon: '⚗️', points: 115, type: 'drag-sort' },
  { id: 'sci-7-4', title: 'Cell Biology', subtitle: 'Prokaryote vs Eukaryote', icon: '🔬', points: 110, type: 'drag-sort' },
  { id: 'sci-7-5', title: 'Forces & Motion', subtitle: 'Speed & Velocity Lab', icon: '🏎️', points: 110, type: 'sequence' },
  { id: 'sci-7-6', title: 'Ecology', subtitle: 'Biome Comparison', icon: '🌍', points: 110, type: 'matching' },
  { id: 'sci-7-7', title: 'Human Body', subtitle: 'Circulatory System Journey', icon: '❤️', points: 115, type: 'sequence' },
  { id: 'sci-7-8', title: 'Scientific Inquiry', subtitle: 'Variables & Controls', icon: '📋', points: 115, type: 'drag-label' },
  { id: 'sci-7-9', title: 'Astronomy', subtitle: 'Galaxy Types & Black Holes', icon: '🌌', points: 115, type: 'click-identify' },
  { id: 'sci-7-10', title: 'Climate Science', subtitle: 'Greenhouse Effect Model', icon: '🌡️', points: 115, type: 'drag-sort' },
];
LESSONS.science[8] = [
  { id: 'sci-8-1', title: 'Physics', subtitle: 'Newton\'s Laws Lab', icon: '🍎', points: 120, type: 'sequence' },
  { id: 'sci-8-2', title: 'Chemistry', subtitle: 'Periodic Table Explorer', icon: '⚗️', points: 120, type: 'matching' },
  { id: 'sci-8-3', title: 'Earth Science', subtitle: 'Climate Systems', icon: '🌍', points: 125, type: 'drag-sort' },
  { id: 'sci-8-4', title: 'Biology', subtitle: 'DNA & RNA Basics', icon: '🧬', points: 120, type: 'drag-label' },
  { id: 'sci-8-5', title: 'Waves & Sound', subtitle: 'Frequency & Amplitude', icon: '〰️', points: 120, type: 'matching' },
  { id: 'sci-8-6', title: 'Chemical Reactions', subtitle: 'Balancing Equations', icon: '⚗️', points: 125, type: 'sequence' },
  { id: 'sci-8-7', title: 'Space Science', subtitle: 'Space Exploration Timeline', icon: '🚀', points: 120, type: 'sequence' },
  { id: 'sci-8-8', title: 'Electricity', subtitle: 'Circuit Builder', icon: '⚡', points: 125, type: 'drag-label' },
  { id: 'sci-8-9', title: 'Ecology & Humans', subtitle: 'Human Impact on Earth', icon: '🌱', points: 125, type: 'journal' },
  { id: 'sci-8-10', title: 'Scientific Method', subtitle: 'Full Lab Report', icon: '📋', points: 130, type: 'journal' },
];
LESSONS.science[9] = [
  { id: 'sci-9-1', title: 'Biology', subtitle: 'Cell Division & Mitosis', icon: '🔬', points: 130, type: 'drag-label' },
  { id: 'sci-9-2', title: 'Chemistry', subtitle: 'Stoichiometry Intro', icon: '⚗️', points: 135, type: 'drag-sort' },
  { id: 'sci-9-3', title: 'Ecology', subtitle: 'Carrying Capacity Lab', icon: '📊', points: 130, type: 'click-identify' },
  { id: 'sci-9-4', title: 'Genetics', subtitle: 'Punnett Square Practice', icon: '🧬', points: 130, type: 'drag-sort' },
  { id: 'sci-9-5', title: 'Evolution', subtitle: 'Natural Selection Simulation', icon: '🦕', points: 130, type: 'sequence' },
  { id: 'sci-9-6', title: 'Physics', subtitle: 'Kinematics: Speed vs Velocity', icon: '🚀', points: 135, type: 'click-identify' },
  { id: 'sci-9-7', title: 'Lab Skills', subtitle: 'Safety & Measurement', icon: '🧪', points: 125, type: 'drag-label' },
  { id: 'sci-9-8', title: 'Earth Systems', subtitle: 'Biogeochemical Cycles', icon: '🌍', points: 130, type: 'matching' },
];
LESSONS.science[10] = [
  { id: 'sci-10-1', title: 'Chemistry', subtitle: 'Moles & Reactions', icon: '⚗️', points: 140, type: 'sequence' },
  { id: 'sci-10-2', title: 'Biology', subtitle: 'Evolution & Natural Selection', icon: '🦕', points: 145, type: 'matching' },
  { id: 'sci-10-3', title: 'Thermodynamics', subtitle: 'Heat Transfer Lab', icon: '🌡️', points: 140, type: 'click-identify' },
  { id: 'sci-10-4', title: 'Anatomy', subtitle: 'Organ System Interactions', icon: '🫁', points: 140, type: 'drag-label' },
  { id: 'sci-10-5', title: 'Chemical Bonding', subtitle: 'Ionic vs Covalent', icon: '🔗', points: 145, type: 'drag-sort' },
  { id: 'sci-10-6', title: 'Waves & Light', subtitle: 'Electromagnetic Spectrum', icon: '🌈', points: 140, type: 'sequence' },
  { id: 'sci-10-7', title: 'Ecosystem Dynamics', subtitle: 'Population Graphs', icon: '📈', points: 145, type: 'journal' },
  { id: 'sci-10-8', title: 'Scientific Research', subtitle: 'Peer Review Process', icon: '🔬', points: 145, type: 'journal' },
];
LESSONS.science[11] = [
  { id: 'sci-11-1', title: 'Physics', subtitle: 'Electricity & Magnetism', icon: '⚡', points: 150, type: 'drag-label' },
  { id: 'sci-11-2', title: 'Environmental Science', subtitle: 'Sustainability Project', icon: '♻️', points: 155, type: 'journal' },
  { id: 'sci-11-3', title: 'AP Chemistry', subtitle: 'Equilibrium & Kinetics', icon: '⚗️', points: 155, type: 'drag-sort' },
  { id: 'sci-11-4', title: 'AP Biology', subtitle: 'Protein Synthesis', icon: '🧬', points: 155, type: 'sequence' },
  { id: 'sci-11-5', title: 'Physics: Optics', subtitle: 'Lenses & Light Bending', icon: '🔭', points: 150, type: 'click-identify' },
  { id: 'sci-11-6', title: 'Neuroscience Intro', subtitle: 'How the Brain Works', icon: '🧠', points: 155, type: 'drag-label' },
  { id: 'sci-11-7', title: 'Climate Solutions', subtitle: 'Engineering for Earth', icon: '🌱', points: 155, type: 'journal' },
  { id: 'sci-11-8', title: 'Research Methods', subtitle: 'Lab Design Capstone', icon: '📋', points: 160, type: 'journal' },
];
LESSONS.science[12] = [
  { id: 'sci-12-1', title: 'AP Science Topics', subtitle: 'Lab Design & Analysis', icon: '🏆', points: 165, type: 'journal' },
  { id: 'sci-12-2', title: 'Senior Capstone', subtitle: 'Independent Lab Report', icon: '📋', points: 170, type: 'journal' },
  { id: 'sci-12-3', title: 'Quantum Physics', subtitle: 'Intro to Quantum World', icon: '🌀', points: 170, type: 'click-identify' },
  { id: 'sci-12-4', title: 'Genomics', subtitle: 'CRISPR & Gene Editing', icon: '🧬', points: 170, type: 'highlight' },
  { id: 'sci-12-5', title: 'Astrophysics', subtitle: 'Big Bang & Dark Matter', icon: '🌌', points: 170, type: 'sequence' },
  { id: 'sci-12-6', title: 'AP Physics', subtitle: 'Free Response Practice', icon: '📝', points: 165, type: 'journal' },
  { id: 'sci-12-7', title: 'Bioethics', subtitle: 'Science & Society Debates', icon: '⚖️', points: 165, type: 'journal' },
];